### ISSUE TITLE
Error "key was too long" while migrating

### ISSUE THREAD

**Issue by highsolutions** [JeffreyWay/council#10]
On MySQL database server older than 5.7.7 `php artisan migrate` generates error "key was too long". 

To solve this you need to add line: `\Schema::defaultStringLength(191);` to AppServiceProvider@boot.

**Comment by highsolutions** [comment]
PR https://github.com/JeffreyWay/council/pull/11 solves this problem.

**Comment by NathanGeerinck** [comment]
Or you could update your MySQL version?

**Comment by highsolutions** [comment]
@NathanGeerinck sure, but not every one can update MySQL version (especially on shared server).

**Comment by joshmanders** [comment]
This should be a note that is put in the readme if anything, not by default for everyone.

**Comment by philip** [comment]
FWIW: MySQL 5.7 went GA with 5.7.9. Also, versions before 5.7.7 were milestone releases (and not even release candidates). That said, I don't think it's worth worrying about these old releases.

**Comment by highsolutions** [comment]
This is problem for all versions before 5.7.7, so also 5.5 and 5.6. But I agree that putting this line of code for everybody may be unnecessary and just adding Troubleshooting section with hint what to do will be enough. However it's always one step more to do to install project.

**Comment by philip** [comment]
Interesting, thanks, seems 'just work' should be default Laravel behavior as MySQL 5.5/5.6 are still maintained and popular today. If this is the fix then imho it should be added to the code and not the docs. If it's a performance issue then maybe execute it if the MySQL version is before 5.7.
