### ISSUE TITLE
Failed ProfilesTest (not seeing user name)

### ISSUE THREAD

**Issue by flightphysical** [JeffreyWay/council#114]
As posted it seems that ProfilesTest fails for a_user_has_a_profile(), but everything seems to be working, does anyone else get this, should that just be skipped too?

**Comment by ruman63** [comment]
All tests passing for me.

**Comment by MattMangoni** [comment]
same here

**Comment by Douglasdc3** [comment]
@flightphysical  could you post the output (stack trace of the test) ?

**Comment by bambamboole** [comment]
@ruman63 this is the right way. We should only assert against data in the view or session. Assertions against rendered html can break by small changes.

**Comment by flightphysical** [comment]
You guys are awesome!
