### ISSUE TITLE
[Enhancement] Show channel name in the footer of each threads panel, on the threads list page 

### ISSUE THREAD

**Issue by arifkhn46** [JeffreyWay/council#125]
The title of this issue is self-explanatory. Channel name will be a link so that a user can click on it and will get the list of threads associated with that channel.

![channel-label-on-threads-list](https://user-images.githubusercontent.com/12694008/35387433-bed87e0e-01f5-11e8-99ba-e31d6cec2691.png)

**Comment by JeffreyWay** [comment]
Done.
