### ISSUE TITLE
Move to WorkBench

### ISSUE THREAD

**Issue by papi83dm** [JeffreyWay/council#131]
Would it be possible to move this project into a workbench directory so it lives outside of laravel and  have all the codes in something like 

Workbench/JeffreyWay/Council/?

**Comment by davorminchorov** [comment]
Yeah, but it is not exactly built as a package at the moment. You have to customize it yourself.

**Comment by JeffreyWay** [comment]
Yeah as @davorminchorov said, it's not meant to be a package at the moment.
