### ISSUE TITLE
Idea of screencast about git

### ISSUE THREAD

**Issue by YouzOnline** [JeffreyWay/council#133]
Hello,

Maybe it's already planned, but it could be cool to have a screencast speaking about milestones or version control for the master, I don't know if both are the same things or not..

I mean have a version of the project locked to a certain version for example 1.9, then they are others version like 2.0 who include breaking changes. But peoples can continue to use the 1.9.

What do you think about that ?

**Comment by davorminchorov** [comment]
The forum was not built as a package, so I am not exactly sure how it would work with versioning. Packages usually work with versions so until the forum is converted to a package, you have to probably do it yourself.

**Comment by bambamboole** [comment]
I think he means release tags which are really useful.

**Comment by JeffreyWay** [comment]
Yes, the series will cover tagging 100%.
