### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by davorminchorov** [JeffreyWay/council#135]
Hey Jeffrey,

I know that you don't use Docker but I think it would be a good idea to support multiple development environments for people who don't use Laravel Valet like me. (I am on Windows)

I can create a pull request with a basic LEMP stack.

What are your thoughts?

**Comment by mludi** [comment]
I thought too about that. Currently I think devs which like to use docker, they can drop the project into their own stack.

**Comment by jonsugar** [comment]
I'm using [Laragon](https://laragon.org/) on Windows and that works for me. It provides all the Laravel Valet functionality plus lots more...

Having said that I do like the idea of a docker environment. I've been meaning to check out docker but never got round to it.

**Comment by JeffreyWay** [comment]
I think we can probably skip anything Docker-specific for this project.
