### ISSUE TITLE
Default seeders instead of tinkering

### ISSUE THREAD

**Issue by highsolutions** [JeffreyWay/council#14]
We think that much easier is just execute `php artisan db:seed` instead of tinkering and generating fake channels and threads every time we need clean slate.

**Comment by highsolutions** [comment]
PR https://github.com/JeffreyWay/council/pull/15 solves this issue.

**Comment by JeffreyWay** [comment]
Merged. Thanks again!

**Comment by highsolutions** [comment]
Our pleasure @JeffreyWay . Each time you create new threads in tinker, I thought - if I have chance, then I will prepare seeder for you, for not doing this N time :smile:. And dreams come true :smile:.
