### ISSUE TITLE
It is impossible to register two users with the same name.

### ISSUE THREAD

**Issue by MattMangoni** [JeffreyWay/council#149]
And that shouldn't be unique, since that's a real person name. And two different people can have the same name. Here in Italy my name is actually quite common, for example :)

That would require some changes in the way we handle user profiles though.

Here's a couple of possible solutions I thought about:
- making names not unique and start fetching profiles by ID.
- making names not unique and create a unique user slug for fetching profiles.

**Comment by jonsugar** [comment]
It is important to have a unique identifier for the person that posted the thread, however, I agree that making the name unique is a bit weird. 

Another approach could be to introduce a username field that is unique and use that for fetching the profile and identifying the user in the thread title. The real name could be made optional but if the user wants to add their name then they can.

**Comment by MattMangoni** [comment]
@jonsugar that could be a nice solution :)
