### ISSUE TITLE
Threads List Queries Optimization

### ISSUE THREAD

**Issue by arifkhn46** [JeffreyWay/council#150]
On the Threads list page, we should not check for subscription, for an anonymous user.

Is there any way to minimize the queries.

![threads-list-queries](https://user-images.githubusercontent.com/12694008/35746341-807c857e-086c-11e8-95eb-31fe80764c79.png)

**Comment by tykus** [comment]
I have made PR #144 which deals with the N + 1 queries - the anonymous user is not relevant in that case.
