### ISSUE TITLE
How to handle Scout backend exceptions?

### ISSUE THREAD

**Issue by Corben78** [JeffreyWay/council#169]
As the Thread model is using the Searchable trait, every create method is sending the data of the thread instance to the indexer.
I'm using elasticsearch as driver, and when the service is offline, I get a `\Elasticsearch\Common\Exceptions\NoNodesAvailableException`.
As I don't want the application to stop working just because the indexing service is not available right now (it would get updated later somehow when available again), I thought I would just catch this exception in the `ThreadController@store` method and continue like this:
```php
public function store(Recaptcha $recaptcha)
{
    request()->validate([
        'title'      => 'required|spamfree',
        'body'       => 'required|spamfree',
        'channel_id' => 'required|exists:channels,id',
        'g-recaptcha-response' => ['required', $recaptcha],
    ]);

    $flashmsg = 'Your thread has been published';

    try {
        $thread = Thread::create([
            'user_id'    => auth()->id(),
            'channel_id' => request('channel_id'),
            'title'      => request('title'),
            'body'       => request('body')
        ]);
    } catch (\Elasticsearch\Common\Exceptions\NoNodesAvailableException $e) {
        $flashmsg .= '. Elasticsearch temporarily offline.'
    }

    if (request()->wantsJson()) {
        return response($thread, 201);
    }

    return redirect(action('ThreadController@show', [ $thread->channel, $thread ]))
        ->with('flash', $flashmsg);
}
```
My problem now is that the `$thread` variable is not set when this exception is thrown (Undefined variable: thread) but the thread was saved the database. Also the `static::created()` method of the `Thread::boot()` method is not trigged, so I neither have a slug nor got the reputation increased by 10.

What is the proper way to handle this situation?

**Comment by Corben78** [comment]
Okay, this seems to work as intended, but I'm not sure if it's the proper way to do it:
```php
public function store(Recaptcha $recaptcha)
{
    request()->validate([
        'title'      => 'required|spamfree',
        'body'       => 'required|spamfree',
        'channel_id' => 'required|exists:channels,id',
        'g-recaptcha-response' => ['required', $recaptcha],
    ]);

    $flashmsg = 'Your thread has been published';

    $thread = new Thread([
        'user_id'    => auth()->id(),
        'channel_id' => request('channel_id'),
        'title'      => request('title'),
        'body'       => request('body')
    ]);
    try {
        $thread->save();
    } catch (\Elasticsearch\Common\Exceptions\NoNodesAvailableException $e) {
        $flashmsg .= '. Elasticsearch offline.';
    }

    if (request()->wantsJson()) {
        return response($thread, 201);
    }

    return redirect(action('ThreadController@show', [ $thread->channel, $thread ]))
        ->with('flash', $flashmsg);
}
```

**Comment by Joucke** [comment]
This can (and should?) be solved by queueing the scout operation, right?

**Comment by jryd** [comment]
@Joucke correct - the queuing obviously takes care of this syncing asynchronously and so no issues should effect the user.

If Algolia is down, the queue should just take care of retrying this automagically.

**Comment by Joucke** [comment]
So check the value of SCOUT_QUEUE in your .env, it should be set to true in order to enable queueing.
