### ISSUE TITLE
Replace 'scope' w/ 'slot-scope'

### ISSUE THREAD

**Issue by wdvio** [JeffreyWay/council#176]
https://github.com/JeffreyWay/council/blob/228cabac5c452bd0286966535124a2ed47549343/resources/views/threads/search.blade.php#L14

I see that there are plans to update Vue version, `scope` is deprecated in the most recent version and must be replaced w/ `slot-scope`.

`<template slot-scope="{ result }">`

**Comment by JeffreyWay** [comment]
Thanks!
