### ISSUE TITLE
Suggestion to extract to a package instead of a project

### ISSUE THREAD

**Issue by Christophvh** [JeffreyWay/council#182]
Hi,

This is something pretty big but it might be nice to extract this project into a package instead of a full Laravel install.

This way it will be possible to integrate the forum inside a existing project. It would also be a nice learning experience on laracasts :)

This is just a suggestion and maybe worth discussing?

**Comment by MattMangoni** [comment]
Oh, that's a big one. Maybe in the future, it would be really nice.
Tbh, I don't see much content dedicated to laravel packages development on laracasts :(

**Comment by manshu** [comment]
Yes, I agree. I want to learn more about extracting packages, but there is only one series about it. I think it will be great idea to start a dedicated series about creating a package using phpunit and make it open source.

**Comment by JeffreyWay** [comment]
It's fairly difficult to extract a full forum like this to a reusable package. It's doable - but an incredible amount of work. For now, that's not a primary focus for this project.
