### ISSUE TITLE
Avatar not loading, even after running 'storage:link' artisan command

### ISSUE THREAD

**Issue by rumansaleem** [JeffreyWay/council#183]
The generated url is - `/avatars/filename.jpeg`
According to symlink, expected url is - `/storage/avatars/filename.jpeg`
I dont know if its same for every one, but for me, `php artisan storage:link` creates the link as:
`public/storage` -> `/storage/app/public`

**Comment by kaxias** [comment]
This happens to those who use apache on windows.

**Comment by ruman63** [comment]
But, I am using php artisan serve on arch linux. Also, this happens when using homestead, I had to reference the links as `/storage/path/to/file`.

**Comment by flightphysical** [comment]
I too am having this problem on my DigitalOcean server and on my Mac OS development version

**Comment by ruman63** [comment]
I think it doesn't happen to people using `valet` on Mac. I am a linux user so I dont have idea about this.

**Comment by flightphysical** [comment]
I'm on a Mac and not using valet (but older OS X.11), and the DigitalOcean server is straight forge script setup on Ubuntu. Only warning I got was a line ending change during one of the git pulls. Everything else seems to be working as expected.

**Comment by lb308** [comment]
login to your system (homestead..) vagrant ssh, then run php artisan storage:link

**Comment by ruman63** [comment]
@lb308 what if I am running `linux-valet` or `php artisan serve` ??

**Comment by ruman63** [comment]
@lb308 what if I am running `linux-valet` or `php artisan serve` ??

**Comment by lb308** [comment]
@ruman63 this problem i have it in windows 10 with `php artisan serve` or in xampp server
the image not accessible, but when i change the url from database by adding the folder `storage`
`http://council.test/avatars/me.jpeg`
to
`http://council.test/storage/avatars/me.jpeg`
the image apear

hope it can help to find the solution

**Comment by lb308** [comment]
I am using a hosting and still its not fixed, I login from SSH and do storage:link and still I cant see the avatar picture,

I cant add new tread also its not added to database?

**Comment by lb308** [comment]
its works on valet.
 after install valet and install PHP 7.1 and mysql server
and council install 
and php run dev
php artisan storage:link 

everythings works

**Comment by lb308** [comment]
I think the problem with the avatar showing is related to the php or mysql version
i test the app in hosting but not working like it works in valet

**Comment by lb308** [comment]
I think its related to the php server i try many things and it works will with php => 7.1.14

**Comment by dhamilton47** [comment]
Same problem: using  Wampserver v3.1.3
- Apache 2.4.33
- PHP 7.2.4
- MySQL 5.7.21

**Solution for me:**
Edit the following App\User function:
```
public function getAvatarPathAttribute($avatar)
    {
        return asset($avatar ?: 'images/avatars/default.svg');
    }
```

Change it to:

```
public function getAvatarPathAttribute($avatar)
    {
        return asset($avatar ? '('storage/' . $avatar)' : 'images/avatars/default.svg');
    }
```

**Comment by pmochine** [comment]
Just that you know the valet driver has a backup function to check in storage folder if there is a file. 

Since you are not using valet on your server or xamp etc. It won't work, so that is why you need /storage

**Comment by rumansaleem** [comment]
@pmochine yeah! exactly this is why I created this issue, maybe it works on Mac, but not everywhere. So, `/storage` should be added to public image links, so as to work for every system. But, I believe its obsolete now. So closing this issue. Thanks everyone. :slightly_smiling_face:
