### ISSUE TITLE
It is impossible to mention users.

### ISSUE THREAD

**Issue by rin4ik** [JeffreyWay/council#187]
**at.js** is not working after we move replies to trix editor . I tried make it on **wysiwyg** component but without success.
![screenshot at 2018-02-16 16 42 49](https://user-images.githubusercontent.com/25279578/36312975-dc8a3948-1338-11e8-9e4a-280cb3dbacef.png)

**Comment by JeffreyWay** [comment]
Yeah, this is a known issue. We have another issue already open, so will give this a close.
