### ISSUE TITLE
Trying to get propert of non object in the sidebar

### ISSUE THREAD

**Issue by GabMic** [JeffreyWay/council#213]
I get that the 
```

<a href="<?php echo e(url($thread->path)); ?>" class="link text-blue">
                            <?php echo e($thread->title); ?>
                        </a>
```

What can be the reason? 
and really, on the threads table, I don't have a path column.

**Comment by GabMic** [comment]
In the code here u can see that in the threads migration there is no path column. Is this a mistake?

**Comment by JeffreyWay** [comment]
`path` is a custom accessor on the `Thread` model.

https://github.com/JeffreyWay/council/blob/master/app/Thread.php#L82
