### ISSUE TITLE
No consistency in routes/web.php

### ISSUE THREAD

**Issue by adevade** [JeffreyWay/council#216]
Are we starting URIs with slashes or not...? 😉 

`Route::get('threads', 'ThreadsController@index')->name('threads');`
`Route::get('/threads/{channel}/{thread}/replies', 'RepliesController@index')->name('replies');`

About 50/50 right now 

[Link to web.php](https://github.com/JeffreyWay/council/blob/a9bf9c5ca4ef03ec10d0a7cb3fe2394beceb12d4/routes/web.php)

**Comment by ahjorth** [comment]
You could always submit a PR :)

**Comment by adevade** [comment]
Just thought I'd check which one is preferred first, since it's about 50/50 atm. 

(I know it really doesn't matter, but still...)

**Comment by Joucke** [comment]
Yay, something simple to solve!

Created 2 PR for this, #217 adds the missing slashes, #218 removes them. Up to @JeffreyWay to choose!
