### ISSUE TITLE
Will this forum system be able to work without redis?

### ISSUE THREAD

**Issue by GabMic** [JeffreyWay/council#227]
in the Prerequisites section it says:

> If you want use Redis as your cache driver you need to install the Redis Server. You can either use homebrew on a Mac or compile from source (https://redis.io/topics/quickstart).

Well, what if i dont want it? what is the cache option in that case, and how can i implement one?
Sorry for being a noob here :)
Thanks for all this amazing work.

**Comment by thmsbkkr** [comment]
If you don't want to use Redis as your cache driver, you can use the **database** option. Then the database will be used to store your jobs. You can generate the database tables needed by doing `php artisan queue:table`. 

I hope this helps!

**Comment by GabMic** [comment]
@thmsbkkr  Maybe(probably), you know better than me. In the repo, what is the main use of the cache? what does it cache here? and do i really need it for a low traffic site? in that case, can this forum system be used without any cache?

**Comment by thmsbkkr** [comment]
For the most part it is used for retrieving and storing the **trending threads**. You can find some more information about this in #148.

I've updated my previous comment a little bit, was mixing cache and queue together. :smile:

**Comment by GabMic** [comment]
Thank you very much bro! It helped me alot.

**Comment by thmsbkkr** [comment]
Glad I could help!
