### ISSUE TITLE
Vuejs Error 422 (Unprocessable Entity) on POST

### ISSUE THREAD

**Issue by andjelko** [JeffreyWay/council#228]
When I submit new reply without body I get error 422 (Unprocessable Entity).

**Comment by therealspoljo** [comment]
422 is returned when the data you entered is invalid, in this case the body is empty and validation is not passing. 

[ThreadsController](https://github.com/JeffreyWay/council/blob/master/app/Http/Controllers/ThreadsController.php#L66) `'body' => 'required|spamfree',`
