### ISSUE TITLE
Shared hosting issue.

### ISSUE THREAD

**Issue by GarethCott** [JeffreyWay/council#237]
Iv uploaded the project to a shared hosting server.

what is strange is the app takes a long time to update or send requests or even few some pages. Ill be logged in but then change a view and ill get logged out or for another example ill leave a comment but it wont show, only after about 3-5 min will it come up. Is this a normal thing on hosting servers or am i doing it wrong?

i must also mention that on my localhost it runs perfectly.

**Comment by Mo7sin** [comment]
Most likely it's hosting issue!
