### ISSUE TITLE
Feature Request: Add Travis CI to check if Tests are green

### ISSUE THREAD

**Issue by bambamboole** [JeffreyWay/council#3]
Hi,

it would be nice if we can see the test status within a badge in the readme.md.

**Comment by svenluijten** [comment]
My vote would actually go to [CircleCI](https://circleci.com/). In my experience it's a bit more user-friendly and the configuration and documentation is outstanding (this is especially where Travis lacks in my opinion). Either way, 👍 for CI!

**Comment by JeffreyWay** [comment]
Will do!

**Comment by JeffreyWay** [comment]
Merged in #63.

(Will stick with Travis-CI for now, since I'm a little more familiar with it.)
