### ISSUE TITLE
Adding some issue/PR templates

### ISSUE THREAD

**Issue by m1guelpf** [JeffreyWay/council#36]
GitHub supports adding issue and/or PR templates to pre-populate some things. This can ve very useful when you want to get extra info in issues, or ensure PRs have the quality the project has, or add tests, etc. As an example of an open-source project, we should add this templates.

**Comment by JeffreyWay** [comment]
We're not quite to that point yet, but we'll add an issue template once the project is a little more mature. Thanks!
