### ISSUE TITLE
Receiving real time notification without refreshing the page

### ISSUE THREAD

**Issue by minwea** [JeffreyWay/council#42]

**Comment by m1guelpf** [comment]
Maybe could use Pusher?

**Comment by minwea** [comment]
Yes it can be done easily by pusher but its more challenging if we build using socket.io since pusher is a paid service

**Comment by MattMangoni** [comment]
@minwea I agree, but I'm not sure this is the right place to experiment with that.
I mean, something like that should have a mini-series of its own. :)

But yeah, that would be a wonderful exercise :)

**Comment by JeffreyWay** [comment]
This may be implemented, but it's pretty far down the line.
