### ISSUE TITLE
Call seed on migrating the database

### ISSUE THREAD

**Issue by mludi** [JeffreyWay/council#49]
There is no command provided to use the database seeder.

It's good practice to do that within the `php artisan migrate --seed`

**Comment by NathanGeerinck** [comment]
If you are a developer and you want to contribute to the project then you want to import the demo data. But when you're using the Council application as an application, then you want to have a clean start I guess?

So it's optional to seed the demo data into your database.. This needs to be justified in the installation manual.

**Comment by mludi** [comment]
Oh yeah, you are absolut right, I'll close it.
