### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by svenluijten** [JeffreyWay/council#5]
It's [good practice](https://github.com/blog/1184-contributing-guidelines) to add a CONTRIBUTING.md explaining the best ways for another person to contribute to your project. [Here](https://github.com/puppetlabs/puppet/blob/master/CONTRIBUTING.md) is a good example of one.

**Comment by JeffreyWay** [comment]
Yep, we’ll be tackling this soon. I’ll reference this issue in the video.

**Comment by JeffreyWay** [comment]
Gonna hold off on this for now, while we're still figuring things out.
