### ISSUE TITLE
Users can reply without account confirmation

### ISSUE THREAD

**Issue by MattMangoni** [JeffreyWay/council#51]
Users can successfully post a new reply without having their account confirmed.

Still not sure if it's intended or not, but I think this shouldn't be allowed :)

**Comment by m1guelpf** [comment]
For reference, here's the code that adds replies:
https://github.com/JeffreyWay/council/blob/0d7a741d04780e181e8d8fb0b4794a15682de17e/app/Http/Controllers/RepliesController.php#L38-L48

**Comment by m1guelpf** [comment]
@MattMangoni Opened #52
