### ISSUE TITLE
Awarding "favorite" reputation to wrong user?? 

### ISSUE THREAD

**Issue by tykus** [JeffreyWay/council#56]
Isn't this incorrect; if I am aigned in and favorite a reply by @JeffreyWay, then he should get the points, not me!

https://github.com/JeffreyWay/council/blob/5041b53ba7eaade9a8d76f11795ada422aac5df7/app/Favoritable.php#L39

**Comment by JeffreyWay** [comment]
Ugh, yeah I'll fix that right now. Good catch. Thanks.
