### ISSUE TITLE
Connection refused [tcp://127.0.0.1:6379]

### ISSUE THREAD

**Issue by simoebenhida** [JeffreyWay/council#66]
where this issue comming from ?
![screen shot 2018-01-11 at 7 37 08 pm](https://user-images.githubusercontent.com/19809072/34843655-fc0265dc-f706-11e7-999d-f03696cc4aba.png)

**Comment by roberthamel** [comment]
This is happening because you need to install redis-server on your local machine.

Fix if using MacOS and Homebrew:
1. Install redis with homebrew
`brew install redis`
2. Start redis server
`brew services start redis`

**Comment by JeffreyWay** [comment]
In your `.env` file, change your `CACHE_DRIVER` setting from redis to file.

**Comment by JeffreyWay** [comment]
Whoops, @roberthamel beat me to it. :) Closing this now.

**Comment by philip** [comment]
@JeffreyWay Convert this to a documentation bug?
