### ISSUE TITLE
Install command not working as intended

### ISSUE THREAD

**Issue by toniperic** [JeffreyWay/council#72]
There seems to be an issue with running migrations when prompted by the install command. This is the error I get when trying to do a fresh install:

> SQLSTATE[HY000] [1044] Access denied for user ''@'localhost' to database 'forge' (SQL: select * from information_schema.tables where table_schema = forge and table_name = mi
  grations)

**Steps to reproduce**
Clone the repo and follow installation instructions from README.  
When prompted with the question whether you want to migrate the database, enter `yes`.

**Summary**
1. In the fresh installation process you get to run `php artisan council:install`.
2. At that point there's no `.env` file.
3. As the install command gets triggered, you get prompted for database credentials.  
Regardless of what you type in, at that point the application was already bootstrapped, so the database credentials got stored to `.env` file but never picked up by the application instance.

If you re-run install command after seeing that error _(and even provide invalid data this time)_, the migrations will work because `.env` file exists at the boot time.  
That means the application instance will load up with correct environment variables, the migrations will be ran successfully, and the .env file will get populated with invalid data.

**Comment by MattMangoni** [comment]
Should be fixed by PR #73
