### ISSUE TITLE
Maybe we should think of a better way to handle administrators

### ISSUE THREAD

**Issue by MattMangoni** [JeffreyWay/council#74]
Having their emails listed in a config file is ok to bootstrap things, but not good enough to stay there much longer :)

Tbh, I think a forum will need - at some point - a real roles system, but at first maybe we could add the isAdmin column directly to the users and make the user create him during the installation process.

**Comment by jonsugar** [comment]
I agree that in the long term we probably need a roles system. But until then I think the config file is fine. Perhaps the install command could create the user and add the email to the config file.

**Comment by NathanGeerinck** [comment]
@jonsugar Everything is possible, but if you want to create more ranks on your forum (eg. moderator) then you should looking for a role system.

I like using the role system of Spatie: https://github.com/spatie/laravel-permission

**Comment by jonsugar** [comment]
@NathanGeerinck what I was trying to say is that when there is a PR which implements a feature that requires ranks then that PR can also implement the roles.

**Comment by MattMangoni** [comment]
@jonsugar or this can be done in a dedicated PR, I'm just saying that this should be something to implement at some point. You did a great job by creating some nice foundations to build upon, btw :)

**Comment by JeffreyWay** [comment]
I don't want to add a roles system until we absolutely need it. Not saying we won't, but the basic admin setup is fine for now, I think. 

(Fun fact, the Laracasts forum, which receives millions of visits a year, doesn't have any sophisticated role system. Just full admins and regular users.)
