### ISSUE TITLE
Roadmap (Suggestion)

### ISSUE THREAD

**Issue by Douglasdc3** [JeffreyWay/council#81]
Since this is both open source project and video series on Laracast it could be opportune to include a roadmap either in the readme or in a new file. 

This roadmap could include ideas you have or things you like to work on down the road and also mentioned if you want to do them yourself as a video on Laracast or have the community involved. This would also focus feature request PR's towards what you have in mind as the progression of Council. 

If you prefer to use github issues maybe label issues with milestones and assign features you want to include as part of a video to yourself. While features you want the community to make, can be labeled with `Help wanted`.

**Comment by JeffreyWay** [comment]
Yep - this is on my todo list 100%. :)
