### ISSUE TITLE
Admin Panel  Edit/Remove Channel

### ISSUE THREAD

**Issue by papi83dm** [JeffreyWay/council#85]
Would be nice  to add the function to edit/remove a channel.

**Comment by tomb1n0** [comment]
If i get a chance i'll look at doing this - what do people think should happen when a channel is removed though? Should all the threads in that channel be deleted too or should the channel itself be soft deleted?

**Comment by bambamboole** [comment]
@tomb1n0 
In my opinion a channel can't be deleted if there are threads in it.

**Comment by papi83dm** [comment]
@tomb1n0 the create form is broken because the $channel variable is undefined in the _form.blade.php file.

**Comment by tomb1n0** [comment]
@papi83dm thanks for this - not sure how that happened! Fixed in the PR in any case. On a related note - i've been really busy with my day job so if anyone has some time to kill, feel free to look at the deletion portion of this.

**Comment by JeffreyWay** [comment]
Merged in #88
