### ISSUE TITLE
[Discussion] Moving reputation points to council.php config file?

### ISSUE THREAD

**Issue by MattMangoni** [JeffreyWay/council#87]
I think it would be easier and more logic for the average user to have all the configurable data in the same place.

@JeffreyWay and everyone else: how do you feel about it? Does this approach have any real downside?

**Comment by deframe** [comment]
The only small downside is the amount of refactoring required. The App\Reputation class constants can no longer be used so it's a matter of changing all references to those and updating ReputationTest.

It would be a definite improvement though.

**Comment by JeffreyWay** [comment]
It's fine with me. Unless one of you would like to submit a PR, I probably won't get to it until next week.

**Comment by MattMangoni** [comment]
@JeffreyWay I'll take a look later when I get back home :)

**Comment by deframe** [comment]
A trait with increase/decrease/getReputation would be good. My suggestion would be to pass a string to both increaseReputation and decreaseReputation corresponding to the appropriate config key, e.g. `$user->increaseReputation('thread_created')` would get its value from `config('council.thread_created')`. Keeps things pretty flexible.

**Comment by MattMangoni** [comment]
Maybe we can also rename the variables.
I'm not in love with loseReputation('thread_published'), and I don't want to duplicate or make weird.

Maybe some generic keywords, like "thread_creation" or something similar, would be more appropriate.
