### ISSUE TITLE
Ask for Database port number in installation process

### ISSUE THREAD

**Issue by arifkhn46** [JeffreyWay/council#99]
I have running MySQL on different port, so the installation process fails during migration.

![db-port-issue](https://user-images.githubusercontent.com/12694008/35095767-b78e8fde-fc6f-11e7-8b59-48ca01e3db36.PNG)

**Comment by MattMangoni** [comment]
Like I said, we should probably ask for the host as well, now that we're at it.

**Comment by Douglasdc3** [comment]
To encourage first time contributions it could be helpful to have this as a new issue marked for this purpose.

**Comment by MattMangoni** [comment]
@Douglasdc3 Oh yes, you're right.
